name: Simple Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2003585@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Print success message
        run: echo "Action executed successfully!"
